"""empty message

Revision ID: 358495c049f1
Revises: None
Create Date: 2015-07-30 06:10:44.615765

"""

# revision identifiers, used by Alembic.
revision = '358495c049f1'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
